google_analytics_id: UA-33449675-5

repository: https://github.com/iROCKBUNNY/X

timezone: Asia/Shanghai

name: "..:: X ::.."
alias: X
author: iROCKBUNNY
author_url: http://irockbunny.com
organization: TEELAB
organization_url: http://teelab.net
description: Imagination is reality.
url: http://x.irockbunny.com
contact: contact[at]irockbunny[dot]com

logo: /img/Avatar.png

gems:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor